# Image w/ depot_tools & other prerequisites installed
FROM debian AS depot_tools
RUN <<DONE
	set -eux
	apt-get update
	apt-get install -y \
		curl \
		git \
		python3 \
	;
	mkdir -p ~/.config/depot_tools
	echo '{"is-googler":false,"countdown":10,"opt-in":null,"version":3}' > ~/.config/depot_tools/metrics.cfg
	git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth 1
	PATH=$PATH:/depot_tools update_depot_tools
DONE
ENV PATH=$PATH:/depot_tools

# Checkout v8 sources at the given version
FROM alpine/git AS sources
RUN git clone https://chromium.googlesource.com/v8/v8.git /v8
# nb: You cannot `gclient sync` here because it will try to delete cross-device hard links over
# different layers:
# [cleanup] Failed to remove infra/3pp/build_support/ninja-1_11_1/linux-arm64 in
#   "v8/third_party/ninja": removing the deployed package directory: rename /.cipd/pkgs/1
#   /.cipd/pkgs/URISGa6ZV5UB: invalid cross-device link

# Build `gn` for alpine
FROM alpine AS gn
RUN <<DONE
	set -eux
	apk add \
		clang \
		git \
		python3 \
		ninja-is-really-ninja \
	;
	git clone https://gn.googlesource.com/gn
	cd gn
	CFLAGS=-D_LARGEFILE64_SOURCE build/gen.py
	ninja -C out
DONE

# Configure gclient
FROM depot_tools
COPY --from=sources v8 v8
RUN <<DONE
	set -eux
	gclient config --unmanaged $(git -C v8 config --get remote.origin.url)
DONE
